# Generated by Django 4.0.1 on 2022-01-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_details',
            new_name='Order_detail',
        ),
    ]
